// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ofiador.Infrastructure.Data;

#nullable disable

namespace Ofiador.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515180805_CompraParcelasPagas")]
    partial class CompraParcelasPagas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ofiador.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<decimal>("Limite")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("IdCliente");

                    b.HasIndex("Cpf_Cnpj")
                        .IsUnique();

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime>("Data_Compra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer");

                    b.Property<int>("Parcelas")
                        .HasColumnType("integer");

                    b.Property<int>("ParcelasPagas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("Valor_Total")
                        .HasColumnType("numeric");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpresa");

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.CompraParcela", b =>
                {
                    b.Property<int>("idCompraParcela")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_compra_parcela");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idCompraParcela"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pagamento");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_vencimento");

                    b.Property<int>("IdCompra")
                        .HasColumnType("integer")
                        .HasColumnName("id_compra");

                    b.Property<int>("IdFatura")
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcelas");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("ValorParcela")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_parcela");

                    b.HasKey("idCompraParcela");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdFatura");

                    b.ToTable("compra_parcela");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpresa"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Fatura", b =>
                {
                    b.Property<int>("IdFatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_fatura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFatura"));

                    b.Property<DateTime?>("DataGeracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_geracao");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<DateTime>("MesReferencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("mes_referencia");

                    b.Property<int>("Parcelas")
                        .HasColumnType("integer")
                        .HasColumnName("parcelas");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vencimento");

                    b.HasKey("IdFatura");

                    b.HasIndex("IdCliente");

                    b.ToTable("fatura");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPagamento"));

                    b.Property<DateTime>("Data_Pagamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdFatura")
                        .HasColumnType("integer");

                    b.Property<decimal>("Valor_Pago")
                        .HasColumnType("numeric");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdFatura");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Cliente", b =>
                {
                    b.HasOne("Ofiador.Domain.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Compra", b =>
                {
                    b.HasOne("Ofiador.Domain.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ofiador.Domain.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.CompraParcela", b =>
                {
                    b.HasOne("Ofiador.Domain.Models.Compra", "Compra")
                        .WithMany("CompraParcelas")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ofiador.Domain.Models.Fatura", "Fatura")
                        .WithMany("CompraParcelas")
                        .HasForeignKey("IdFatura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Fatura", b =>
                {
                    b.HasOne("Ofiador.Domain.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Pagamento", b =>
                {
                    b.HasOne("Ofiador.Domain.Models.Fatura", "Fatura")
                        .WithMany()
                        .HasForeignKey("IdFatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fatura");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Compra", b =>
                {
                    b.Navigation("CompraParcelas");
                });

            modelBuilder.Entity("Ofiador.Domain.Models.Fatura", b =>
                {
                    b.Navigation("CompraParcelas");
                });
#pragma warning restore 612, 618
        }
    }
}
